[[redirects]]
  from = "/.well-known/lnurlp/*"
  to = "https://ln.tips/.well-known/lnurlp/0x28310b736222ebb5"
  # Netlify does not support 307 status code
  status = 302
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"