[[redirects]]
  from = "/.well-known/lnurlp/*"
  to = "https://ln.tips/.well-known/lnurlp/0x28310b736222ebb5"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"